# config for analysis run by snakemake

# file giving information on samples
sampledata: sampledata.csv

# parameters for calling viral barcodes from Illumina data, which are assumed as:
# [R2 bind site (optional)] - [upstream] - [viral barcode] - [R1 bind site]
viral_barcode_length: 16
# sequence upstream of viral barcode
viral_barcode_upstream:
  fluHA: ATGTGTTCCAACGGCTCCTTGCAATGCCGGATTTGCATATAATGATGCACCATAGGCGGCCGC
  fluNA: GATAGATAAATAATAGTGCACCATAGGCGGCCGC
viral_barcode_upstream_mismatch: 1 # allow up to this many mismatches upstream
# sequence downstream of viral barcode
viral_barcode_downstream:
  fluHA: ''
  fluNA: ''
viral_barcode_downstream_mismatch: 0 # allow up to this many mismatches downstream
